name: Test building HonKit

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      # パッケージのインストール
      - name: Install dependencies
        run: npm ci
      # HonKitのビルド
      - name: build HonKit
        run: npx honkit build
  pdf:
    runs-on: ubuntu-latest
    container:
      image: honkit/honkit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      # パッケージのインストール
      - name: Install dependencies
        run: npm ci
      # HonKitのビルド
      - name: build HonKit
        run: npm run build